# Generated by Django 5.1.2 on 2024-10-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chat_chat_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_room_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
