# Generated by Django 5.1.2 on 2024-10-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_chat_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_room_name',
        ),
    ]
