# Generated by Django 5.1 on 2024-10-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userfollowing_followed_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user',
            new_name='following_user',
        ),
    ]
