# Generated by Django 5.1 on 2024-10-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_user_userfollowing_following_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='followings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
