# Generated by Django 5.1 on 2024-10-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_followers_alter_user_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowing',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
